### ISSUE TITLE
Android PocketMine-MP Error (2.1.1 apk) (1.4 #413 & #421)

### ISSUE THREAD

**Issue by Alvie** [PocketMine/PocketMine-Android#16]
There is an error in the latest version of PocketMine-MP on android. I am not sure but I believe it is the pathways written inside the .phar (or maybe some other) file. I have the error on the console on this link: http://tny.cz/99449c13

and the crash dump log file is here:

https://www.dropbox.com/s/x4dm8y708orasju/CrashDump_Thu_Aug_14-10.25.02-GMT_2014.log

Can you please fix this? @MCMrARM @shoghicp I know you have been working hard on the app and on making everything else work with 0.9.x so please fix whenever you have time to fix the app

Android version: 4.2.2 Jelly Bean
Device: Hudl HT7S3

**Comment by WalterSJ** [comment]
I agree with you because I have the same problem.

**Comment by pmcgamer** [comment]
MCMrARM I hope you fix this bug As soon as possoble

Error dumplog:

```
# PocketMine-MP Error Dump Sat Aug 16 00:13:42 GMT 2014
Error: array (
  'type' => 'E_ERROR',
  'message' => 'Uncaught exception \'RuntimeException\' with message \'pthreads detected an attempt to connect to a Threaded which belongs to another process\' in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php:320
Stack trace:
#0 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php(320): CommandReader::getLine()
#1 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php(269): CommandReader->getLine()
#2 [internal function]: ConsoleAPI->handle(Array, \'server.schedule\')
#3 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(631): call_user_func(Array, Array, \'server.schedule\')
#4 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(471): PocketMinecraftServer->tickerFunction(1408148022.3218)
#5 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(578): PocketMinecraftServer->tick()
#6 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/Po',
  'file' => 'phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php',
  'line' => 320,
)

Code: 
[311]       return $line;
[312]   }
[313] 
[314]   /**
[315]    * Reads a line from console, if available. Returns null if not available
[316]    *
[317]    * @return string|null
[318]    */
[319]   public function getLine(){
[320]       if($this->buffer->count() !== 0){
[321]           return $this->buffer->synchronized(function (){
[322]               return $this->buffer->shift();
[323]           });
[324]       }
[325] 
[326]       return null;
[327]   }
[328] 
[329]   public function run(){
[330]       $this->buffer = new \Threaded;


PocketMine-MP version: Alpha_1.3.12 #620 [Protocol 14; API 12]
Git commit: 0000000000000000000000000000000000000000
Source SHA1 sum: f6a19a7b366e9d4856852b3440802d4be01db7e1
uname -a: Linux localhost 3.4.0-g03485a6 #1 SMP PREEMPT Tue Mar 18 15:02:27 PDT 2014 armv7l
PHP Version: 5.5.15
Zend version: 2.5.0
OS : Linux, android
Debug Info: array (
  'tps' => 0,
  'memory_usage' => '10.1MB',
  'memory_peak_usage' => '13.43MB',
  'entities' => 0,
  'players' => 0,
  'events' => 1,
  'handlers' => 5,
  'actions' => 14,
  'garbage' => 0,
)


Parameters: array (
  'input' => 
  array (
  ),
  'commands' => 
  array (
  ),
  'flags' => 
  array (
  ),
)


server.properties: array (
  'server-name' => 'Minecraft: PE Server',
  'server-port' => 19132,
  'gamemode' => 0,
  'max-players' => 20,
  'spawn-protection' => '-1',
  'whitelist' => false,
  'enable-query' => true,
  'enable-rcon' => false,
  'description' => 'Server made using PocketMine-MP',
  'motd' => 'Welcome @player to this server!',
  'server-type' => 'normal',
  'memory-limit' => '128M',
  'last-update' => 1408148021,
  'announce-player-achievements' => true,
  'view-distance' => '10',
  'allow-flight' => false,
  'spawn-animals' => true,
  'spawn-mobs' => true,
  'hardcore' => false,
  'pvp' => true,
  'difficulty' => 1,
  'generator-settings' => '',
  'level-name' => 'world',
  'level-seed' => '',
  'level-type' => 'DEFAULT',
  'rcon.password' => '******',
  'auto-save' => true,
  'server-ip' => '',
  'white-list' => false,
  'send-usage' => true,
)


Loaded plugins:


Loaded Modules: array (
  'Core' => '5.5.15',
  'date' => '5.5.15',
  'ereg' => false,
  'pcre' => false,
  'sqlite3' => '0.7-dev',
  'zlib' => '2.0',
  'bcmath' => false,
  'calendar' => false,
  'ctype' => false,
  'curl' => false,
  'fileinfo' => '1.0.5',
  'filter' => '0.11.0',
  'ftp' => false,
  'gmp' => false,
  'hash' => '1.0',
  'json' => '1.2.1',
  'mbstring' => false,
  'mcrypt' => false,
  'standard' => '5.5.15',
  'SPL' => '0.2',
  'pcntl' => false,
  'mysqlnd' => 'mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $',
  'Phar' => '2.0.2',
  'posix' => false,
  'pthreads' => '2.0.8',
  'Reflection' => '$Id: 31d836a7ac92a37b5c580836d91ad4736fe2f376 $',
  'shmop' => false,
  'sockets' => false,
  'mysqli' => '0.1',
  'tokenizer' => '0.1',
  'Weakref' => '0.2.4-beta',
  'yaml' => '1.1.1',
  'zip' => '1.11.0',
)
Memory Usage Tracking: 
AwA=


phpinfo(): 
7Vx7c9s4kv+fnwKVnbpJ9qy3ZMnZzdYptpK4Rra0kpK5mb07FkiCEmOS4PBhW6778NcNgCRIUXK8
N5e6utukTIHoH16NRnfjxWgXeaHLX78xlp+W5AuLE4+H5N1fyKg9avdGhrHeJykLMGbuhdkj8blN
/R1PUjJoD9vd1rY7GE5G9Jz8oUfWN0uyXM1mN8sN2WSM3NCY9CakN3rb7b/tj8nyakP63d6Q0Di4
H/vG+8zzHXJFU4b5T7MtISMJ6F287Q/fDi+MSx663jaLGbnkQUBDB5Hkx3bHzgk/wmurxUJq+azl
hb4XshaPUi/wnmgKjfkRyVHMXO/xXeeexh3fszpfWXjnhUnnK7eSDrS8teT2HUtvMPE0dGLuOZ0H
Ht8lEbUZlBVEng+/MU+S/IVKWEu0pWN5YSfaRSNRGntk9ncu8sFLdy07i/3vWuATlPPdC2w5Xvxd
C93T4PuyNbDjfZR+1yK3QfQ9y+NZ2gpBXBOWVOJiRh0cwT9qYzqwkjT2wq0eBzqIhQ6N9bgHRu9g
zOlRUbrDHJOmuFbEHBqmni2IjpcIKjT/MfArUfV3hweV98QLIp81pMJiWFyPfYi9tBZrb71qjixJ
cs1VlMqsbFuJiRxe4V3EFD/yCA905H0V4vBW8psPFSh7PlIcyNmzq3LVTvdRpTsSIQsVliaQhjnv
Ql6JTEH92u/2rAYNeFTpXeqFKfyxuPWkci3YsONx2krptpLDE3Q88HwbUr/ar3aY+noECyzmOMxp
BXtsc6VQjAkdbcQJyDs9XkEtO6DprsKRal5PXqU9bhpp6grreh+8+7jYLEQsGs53MCZaWXgX8ocQ
5A2MaiuDPC17G2aMWt4hExF1V2GNF92f6zge2dTeMewCY83iexaT6fIabWVuNsF6M3Idgui5MGiN
L16cZtQnV17M7JTHe7LOogj4jWlkpk5hfIUdJR9gXJPXMIzbXui9IUtgC4L/57UG5m7MOQwmhzRU
CerwOuQhe2OsbRqSdOclBEwEcXlMqON4iISWYq2JCwkSLcW0kR5RUEyOBkPfSPET3JN+r9cbiLjZ
Y8rC3GMSFPhv/Aq9XiMdo0kPCJ2f5XUBOtusa7lXYBrqCpVCSQ25sRHKjaypy9K93pei4LUYNuQT
8BlEantAv2EBisINDekWROiAnPmpZ+3BXdOEJYr5vYddY+1JrqqN6+X9uQ5ScusYV5sYer+RZKzY
1gNnE1QJweavU2hKIHoL5SMGpdhG+39GQCjORFedka3PIcKhKT0juzTFeHygFjsjMDT1TGWGZC3E
kkBFwgQrIUpIbUiVOfgIvUcMbhuSgrzBu0iANWn/8YxIWy1CDivCkg3tmKe9QfGWcmg1i7V3nz9o
7/gTmajvzgiqbhaLvCCYZAFzoJnM3oHiMKCXQcaB8dsYKhXQO5DZLGGEuyD9jMiutiGzFDt5TsNt
Bv1JZuEWxuJbJYPihdz3wc/vnsG4ivaxt92l5LX9Btzvi0lLOOICu4FyQ6js1mOJYRjE/H3+QVaV
4WwYUtkaxvvLG9QuyaFKMqTC8u7FuJ/jZIR8oX4mXm8odpd8V3m1E3QVkNgVD8PIXQcoXIUay7nk
MTOOTYq+uRLUhy42wS03XR4xkcdCPTWaF9p+5ojUC9dVP0B/oPvEjHiU+TBFMmP6AC9JaqK017Hx
1kwY6C0Kuhw0WZSJ1vyTeNSo4AjUyImUunqeWcpNChIbOqarFG3IyX3e0DwsgTgQwSKbX7202kok
wuB9Phsr5g/QW9FRgMNcChrItHeon0UxWeq2Jo2gwAsYui5icLPHtLNLA7/yYijNY9o+TRJpFprL
VTg3C22U05PIyKd7k8Uxl2pivblafN6UoQIClh0scKRBFcuA8w63zZjz9Hg53AZP14SWPAc5mY0U
dtPxKz2mYgtRM9GiKGtRgrDauXRI/XW8GIEF9fEMIpeSb8oOsDBkFW7QH5+Pq6BHLzV5aKYgBlxK
uyba7BFaB03cRdVG5QbXRP/hu/k2GOgUZSedkEtvHx3iVm7u/5dVx8ChbGaRD25ZUmHiDqyIj5ak
DUUFLBS8/7PLIZCke5+9e2WDKYnfkj98+DDpdruv/qICf+4g6C8vhGvlqaF/NANI1H3/HjKQgefK
a4Zr5eUa5WhqUVsZ+JbCDuFaYXdsDz3qnMhgPFYZYOD58prgWnnlIGxMf3Wl6isDzxXXDDeQg7oG
LEcoOKpggHGUM7B9zreBEp7FNmsGgX8E+spSZl6nw+zds0FbuH6W7CqirOyyGampDnqVbzudTgJm
FByqDguEZXY63U45ALVg62bZxjQdTNx+a4AKbG5ISTAD+mj60lPodfvD/NeAebLfhumM+WjuxLpC
LQtBhymPzdAsxNREcw8mULmrjZpUpDmll7EyuJiZodkTulTzpJBY1wL9rnwKonBDzJAlqKahUfdM
DJfzoXxqmDznVk8+NRKovEQyodvNf41AzFNM3wukt9HrT27yXwMdLdOiMIOTSryxZdIJMq3MdVku
6KpdirTDSRI7noOwj1jPxHsSFFkFqADYMdvLXcae7MKhAVbUR0EyxUy9SNU7/0n91BFp6ss2ddUP
AOSExASHzsbHfUVcpUk0gTk+o3dJEw0XJEyhzWviE7PfMugoE1TMiTYnkByFxnRjHjyPysdNJ0vi
ToI2JieRVkpaHjlJhHxij/rAJ7PK0bF8GmJ9yBTdDe5rrUHrm80Sw+V+hf5iJEEambnT3x/Jp5H8
5rcTmDqbAT9wxxPwxVMWROYpsYKBZ981j/EsLNsDtfAtRKJLeTQzOa7MfJzlEtO/kc+cnj5TJ6H5
ngV4odeuyN1Ajjf4KQFYjZDKsdrGWLFoor8YMF499B+TUpRmH5eX6yJg4MpoZEsmmWEWWBKlRp9O
rbMQpResfApzLxOm6XbeSbmQC7pyX7f2ISko1i8a8k3EhNlkIWR7yv2UYLGQAjMRZt/VMjPEiqn6
IZU5QzG5xI0aeH5ezZvmniL+OgRlHshlLqCN24Nxu9u6mn0xpltRoYHxAaxeFsOUfJrsQ3t3dSuY
/AtEXILRgam1UA+3XC0TyfDH9bp1y7Y89dS2G8RdX93mIVy3kcG72Bqq4BxUDcvnbpg/eIlPefh2
M79ROAz+/F69rJe3s4+L/GU9z/HrtVxIg9jNfN1ar5bqbRnzlIPDIFglV3dctaCT5Is7+EyMT2o4
P7OQKkrVZu9L7tMY4jq99qA9Nn6de5ZO7rX77YlhwJSHyWdHmKWGDnq18BMeviIboD/xkOEWJkWL
o2eHyyftkXGIAZqH67AgQNAz0mVNcxQQP95sXrDCgBXNPV8TvBEvVSsJg157fC5nRSpYw/JwW4JH
7f5gMNCCEpxkYezBTAmE3pO6/KLbHk0GClu8FGiYl38jWG9y40CDiR7bilVB9kigr2IaixXN9xka
Zof4KqoYVSgzuJldhpo6717vcaiSQAM/DeNaLJsAWz1HjjtcN5dLfrXF0hW7L8zRD9fOWzJ0BpOL
C9adXLBzNhxZvdH4YjyyGXP71B6DwT1nF874vE9+eEHXynrp0xrgL1qnmD5U32pQcGXVck4zY2FE
GcYHsI9NC1/bIBKPJuLHmyXR+HcO/Osaxo4mO/lsSvMJ4pF9csFR1Cpw+vA3hL8RSXa0h48++Lr4
MzrHn8FEvI1g3gtamQUOeHZ56LyrQoiVoQH4SA87L/Yjzn0YTFsWQ4KzgQqed4vgRb8IAmBYAoYl
AIoOmRtn6geL2aLGoegPDvrEju38aRE3vO/BG/6AY/uVU5qSHQVGywrIoKiADIoKiCC0uAiOzguA
qFaRbFgmG5bJhmWyYZlsVCYblclGZbJRmWxEDONrgmuu+GzqNxF/X1WPPcMolviNxt2APHVJVBNJ
Jteb0QnzrMByfePTBiRQLlUWRjfFRXm/sHrF3oBKU63PoN0v60OKFYvqgvirRCzdYzbkjoZfPSLc
BjlgxAhXS+0sfnWGQmTviNhAwmytDGZ3MM7QkcGV9Y+3n8mcJeDrkI8sZDEM3WVmwfQR9JMNpbOi
gsCrts6i119pREH82RsSC4WWnOKZhLzmIa6NZwF9Q9BbFM4lKX2O8GSKe33Z+gJZ9c2KJ+dp7mud
nhQU6LwXzVov6rPUHIt+kcmhjujC6pPKHICW3iwWsiOaJPlvDVMuZz8LMrGri5Vhgf2P12I9+D9p
hKsAosqdR1yW+Ld/Bk/0zTdAypJyq/68D1kk8fO9GaSyLEWJKoMlDn+gI2R/nGBrkkEIrHrKxCo5
tdMTHWfIvav8t0kkJcVUo6UBoDs87RH4T9PIA2dOOkBdXCocG0o9wEiyvWinFiRsELgWanWhWmPv
a+hQ5ouY9IG7HhgTGtsuz2IJRS3s8zvvYqyBL/oETWAc+VlCHmDYE8vnD5i4heucoIod6OYCL4wL
oHFRErQFLdDQHG8bUBLbfYKbcNAySKdVHOeDstqWTWzXInYaE2ZbJMSXkMMD/6SuIS8ZanLLkPpb
HoPTFCQnZ2oKLWpzEmjIAw2ggfD3unFz3/eQD7itnXtSmspQJyFAdXTbvV7LYfekJXa4u6PuAILC
67HcC+qMBlavZ1/Q0Zi5jtXrjsb9i74zHlgX/Yk1sUf2eAxez1RyY4klQPOh4LkXyjWKLjhe9BRZ
pdViXsBfwYe23GsT039QKvlUppgdVlBRWYkGTO5i5UsKzf1UxeasHwy65/nvAebhW3OTB3C+FY0T
8+ewYs0x5+7nUCyryfMPxYsOrTLoNB66iYch9FV9lqwErAgcUSq/txxeqpMEKvskH+GGzWNwZOQ0
tYwVTgUeblCUkKcaNT9bI1cRSb5AM+xenMMUgR4QcJtqIinavtSgNxqc46rmJfd9lGowHOLcD2hy
Oymm9CVRrn7WMDidBn2fW50OzU/MgG4EzyvRmHkmFgDRStvsjGbpzpQYU9DNkOLAMtGK4o5DA8L2
GY0LgIEqpDirUhbklX1brSox0GVJzERJUFe9g6wwKFm6A0ZExTkzDZXH1HBq2UB4E7g0DgP8GEVx
vF6gye9MmXkjlXH3FBn3otWa/LMw12O+Y4L/QZ+FxqiKjmNws5SKzY8kAq6zU1hwBcKt2gLRYTqL
Tbs8X33IauDQEQIw5whF48spRMmSUyjgxhFynRFHYBoPJALwQptC5r9lMMNnyraEPDSP00C4HPaI
2ShOWULgqnEJmpFKQqkIcIuKpSoqCxsio8Rsjm1Eix0riAlxpdBvIERJNRfFK0jBYEiorZ1iIGl0
Hop9JJ2MpzNMl6U2Zozr/5A1HjRUpT8DihINUDRFIGzhiBxm04iq5FMpqJJNkfjb0CV3n8Fr/fM8
8iW54lloHms4CinttOjcJkqFF8mdF0VN8JyQo20e7fFkhDiHbCa0UKRVAhh5XIAuiUI7qNabKedm
AuX4OVXYeDPJbJslSTXSpZ6PFzj0SE8MsnLEVNwEEMXGDKWTaJZZVONLt+QQwh7VJq/t81xFFBu/
WhxM+/OidSQYPs9xfGaCJcg5odGL3N2YMaU8amUcUIo0SRo0V6tOALNvMuQ5t6ESWW4V9Wga1OLt
Zrh9BI47kE34PP4ggWiW3RRZhzZX/Ei9m6t9pNZHKn2szk1Vbqwxg9lc6GRRHXwkGuBH0LVY4ZaY
uKZQKIMwy0dSA9HyjicEf3DvnchYbJEepUJKecLgGPVEnbanyA6zvUILNdBdn9MTqXlm+ew4WW1c
NRL34Jme4FZwOtuTACSCIxtEx7ldnJlpZprPraNEFmbB8YzZcW5tGQfnSW6NNAJ4umMVnlheCLP9
o8JXI9fEr0ZtEMAa4kAEa/QDITykn6zd9jSgQRRriANhrOdwII51QE0ga+S6SB5wMHgu82cgjYJZ
74UD0awzsiacNXJdPOvZs1McbBLRGkQTUi/0itlI4YPqCrQCQO+iSgYKON+e9iYSOJZOZnlt8FVO
QXwv0dLYMZ4pq6RyYh5VImI0dfLMmIxIdlnq8IdQi6nMfGUcMACdGlPsUJYF6g6QDrvzSjcrKA/v
KFDRq/hWCoqE+nQvRhA44XrT6lMhjIT+wFNoTpaLkchPng+uxOX+UTGXlpxQJ5MSn94zvfngw6hZ
RS1W9WwtFs8Aia3p4pS7RtScoSIOOoClB5ngsaB8nVwjCGnTGQQ2P2yegoP3IE8/6w71UVDuXBvi
Fpr6adxejWxxr+ByNSOvlyz28YJWBDKCKmbFtpkPymL2mK9RJW+alm5F6nxHXFssm7QHQ1wcG7R6
/daL7ilgrdrFHpN2sE4eR9WCEgrZZqLYOrQMQSN3eMsCn2/FhZ5pbO+wLg1sQRCZ/etGX4Lut7vt
vqTgClNl6w/+G+svtySub8TT0XAyuRiM6aQ7HAyc4WBI3fPxaOAMHGsy6o1dRt2LnuOSH0TOLXFO
UBzsxO0GrF7lpM7meciv18vnINsnLyruMKna5jQLaP06Md/3JK9h7KY4zYqY7Xesp/4bYxGxEFcj
k8MrVCUcN6zwYFyS+G8M2QdEVhIKwIuieGrcVB1yRniMZhSkw8aJf5TiXa4rGMh7st5R17tryxxc
8BT2BKXee5IXvj7CwMe1yPeM3qvt1BvgQJaQ95zFWxZDSjymjxMxvJ0EmYjbsnguXO4PVi8e9bvd
QQseF3i2hvyEs+Mnn7VfIMhQT3WOLdfnzac3EYcXG3jo7yvr/IoCFiRmpjjUoFPx2Kf3aByeAAGZ
ohcXF2PmjM9B9thoYF/0WNdmk/O+Oxh3x+e9sXUOXPsB8lBXkI3q9lkXjx+tmOvLqasePrI6Lkoe
9JzJ4JyOqX3Rp4OxNbJHky7EOBc96gzHg3OXYQ3OsWRx/Vb9NKondbvXMOQtuaRJ/Rjr5Vw8mnIo
rpgm8vYpmGUknJEFKPv4Gv7wEtIZ6DqhQe5ZGbVm7A6xWkzkLyy5giRe1pn1FRhiXJY3dqbiCkqZ
ZBrHdF97XYhUZ+Q9dT6o83iXMEpmjyjr8CIoNyzdcacWfwmSBBa2zO9SndyUx4LK+OIerRbF8W6z
ltksiFKNjpdXE/F1jUpcJduP4JWVb9ehi64M02Pu8bjSNN5mOKS0wnJMiZ2zcJvuNMgcVbdG51vP
1sjicEGkd8ctX7EHT+c2dOrCfQ+d7CRaShG7QidDj4ROBFf7QYtaglcQajWoJylkpNapRfxB92iU
5n4qAA0dVtCOJjpkakESx9Qa4jcxY3p0FQWjA1w2rckg5Fc439jjbidz5qDDRCQKCx4JLV5ymRav
j8wRLBKvnxiNRODGC8swfSzCMulaXmIQMcvYw+3n/V8zlsmYMrROgY0itGFBpBf9Gc/F1Lr0c8ge
I7E8KfRxQTEM+d2BASiOv84x0KQ8clLAncxnusnvtse4+acQ+nHAQXvSHrYHL3B2VE3aB9e9mrfS
waLiLVG8e7oPaSAO+8jSm1wzPPKeclKcZT95wv0FF0nx0FHapgVY3JTo5fGWKkqdolGx+THz4zc3
JQ5sHXjM7J425PFA41DNMfIi8UanOhmE3+qAuSEedkm0tNWtav0S3nlXPo2TNwjwUmzM5Jcy2vnV
VPoOrKZ7BjpDhVy84PIuie0zXKl+dyamceD7v3sZWh5vh6EQHncXjJTfsRC8HnBoN3mw0Tb+LL9C
IgMw3nH9P0RrePrwDLi67WHLYik1DPzejGGAkP0yvZk3Hq6Tw+NL3SPOk1Ty7bWHL5AzLLvtMDwj
p6boWrfqxOqig0bPj1rRkIeeXREpnY57ZpLh4mpjv0J88Bx5gHjSlU/DwLv8xq9epPOh/EBC3Sfq
jhynx2y73+t1xyP8Gw6sLnMnNmMwQXCcfv/CtW2cBmCe1blFr91FVj5VCcDJLh6AxIv/hjw83tA1
6kMBP8d4NTY++HbB207HqHxLoPiUgBe6eJfsTL7BAMI3cVwB1zcOz6lL+9Bwfv2bu1oUVByMq8w/
9LsRzajyOldxZ0tHPnd5Sv/whpRmcDmVWN/CODWMWXjvxTxErwbcZHWpBPOQlZ/eXq0W11fmarEQ
t6s70pMyZjef59PN7Mpcbxar6ceZuV58Xl3OBCQI006yY75fXNwz5ovF0rxZfL7dLBfXt5sCxi3r
MKvNdPVxpkqr3QAs6vMe6jNfyHsPMCCvzPn1+9V09Yu5nG4+yTu8oC65uMb7VlVafN8EJr+z1e10
npfWWEzHZ1tq743NzfLqetUMqdxFTIOoqNp6cfnTbGM+7bdcLrv0ugXtarqZiuxwNcMo6opG621e
YxFWNU70Fz38CC9FrtP1erZZa93TgVFhTNezyyaew/TUNpB/l3NIWNZBphTqG+80d/CkTvsr3sRs
IIWJPCLXTOd3eBr0aOKYtb5m4GAfAVjg59p7PI3oH6sAuBRHKEXoOXr/CCBlPot2PNzj0caAh0dg
99yLTiOCIDkNUFfD2xH3PXt/BISzMg/s2rE8IpyD4/eujgAemHXvsQd7B36AlwWIKuRmuVosZ6vN
L+bPi9VPIAly/F6clfLaMEjUxzry62dNSsNcz1ZfZqu/vdK1x6t/1/VHATmiSBS6QZUUKWs6RUuB
WuV4AVK95NWpK5iDuueaRiboaeVXlY7K8IjaKatT0z9H6pFroCKdVEXH0AfK6KAZFa2k2tI9hKGC
UoUIFVUAtCb+ndrqoCyptipyIRRXCaxqMK2HhQ4rcBVlVs3vH+rs/746OxCsQ70mhQI12+HAaBqH
mtx/WkJ4/uGbRt7hJwnKjNaXq+vlxryd3sx+r7w+XM9nv0t+OG7MzWp6uxaq8r+d39Xi8vPN7Haj
Kf6SuJr99fNsvTE31zcz88N8MVWI3rA76Q0n3d6kDYFJc4I6tEThNX1JFUs0xmuDwL+/df/Otrwx
Klnbhfqf3X45adgE/eVWTSR7xqQ1Z/2MPavU98CYyWJfZMlkLV5oxkSil9qwStWPGLAK5sB6Cerv
YLoqpRy1WxL1jNESoH9YrP/fFqsiTyfNVXUMNNoq4ZCri5HVTxZCEI/ckYS76QON2Z/InmcEv94Z
s/LmJfFS3FHs8BgXhD13b0BEeRkzZXGQ5N881IoiFArCW5l4BBo3KXP6x5hnkYF7lOrDPhgQ1KJM
XP9QcXhJ6C0h8+vL2e16Zhw0QL8hqpLseATV2tEUa/6AxzYshvdQ3cw/MwBJfr7efMLPwU1vfyE/
T1dg2Da//Imor/MSBuNf5COOgEK2wJqYhukeGmnczFaXnwA/fX89v978QoApH643t7P1mnxYrMiU
LKerzfUl6OAVWX5eLRfrWdswrl3BWcdzxNUVdXKBUIKHfXXe+ZJ3uBWMl4QBEu4N8UkYsXdLLaxg
CfTC7RmJfIbfM4Axn1I7zbP4F/xCbMjStvFf


```

Using Device:Asus Google Nexus7 (2013)
Android Version:KitKat:4.4.4

THX

**Comment by monster12309** [comment]
This I my problem with the second newest version

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 19:09:11 [INFO] Starting Minecraft: PE server version v0.9.5 alpha
[Server] 19:09:11 [INFO] Loading pocketmine.yml...
[Server] 19:09:11 [INFO] Loading server properties...
[Server] 19:09:11 [INFO] Starting Minecraft PE server on *:19132
[Server] 19:09:11 [INFO] This server is running PocketMine-MP version Alpha_1.4dev "絶好(Zekkou)ケーキ(Cake)" (API 1.3.1)
[Server] 19:09:11 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 
[Server] Fatal error: Cannot use pocketmine\block\Block as Block because the name is already in use in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/item/Potato.php on line 24
[PocketMine] Server was stopped.

I am using a kindle fire HD

please fix

**Comment by PEMapModder** [comment]
This is PocketMine issue, and it has already been fixed.

**Comment by droidwwolf** [comment]
Really??

Love,
       Carlos

**Comment by PEMapModder** [comment]
Also, one issue for one bug please, or it will be hard to track.
