### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by NotaGames** [PocketMine/PocketMine-Android#17]
Hey mate I just got thebug fix update but I cant start the server I get this

```







# PocketMine-MP Error Dump Fri Aug 15 11:03:26 GMT 2014
Error: array (
  'type' => 'E_ERROR',
  'message' => 'Uncaught exception \'RuntimeException\' with message \'pthreads detected an attempt to connect to a Threaded which belongs to another process\' in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php:320
Stack trace:
#0 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php(320): CommandReader::getLine()
#1 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php(269): CommandReader->getLine()
#2 [internal function]: ConsoleAPI->handle(Array, \'server.schedule\')
#3 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(631): call_user_func(Array, Array, \'server.schedule\')
#4 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(471): PocketMinecraftServer->tickerFunction(1408100606.7681)
#5 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/PocketMinecraftServer.php(578): PocketMinecraftServer->tick()
#6 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/Po',
  'file' => 'phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/API/ConsoleAPI.php',
  'line' => 320,
)

Code: 
[311]       return $line;
[312]   }
[313] 
[314]   /**
[315]    * Reads a line from console, if available. Returns null if not available
[316]    *
[317]    * @return string|null
[318]    */
[319]   public function getLine(){
[320]       if($this->buffer->count() !== 0){
[321]           return $this->buffer->synchronized(function (){
[322]               return $this->buffer->shift();
[323]           });
[324]       }
[325] 
[326]       return null;
[327]   }
[328] 
[329]   public function run(){
[330]       $this->buffer = new \Threaded;


PocketMine-MP version: Alpha_1.3.12 #620 [Protocol 14; API 12]
Git commit: 0000000000000000000000000000000000000000
Source SHA1 sum: f6a19a7b366e9d4856852b3440802d4be01db7e1
uname -a: Linux localhost 3.0.31-1174257 #1 SMP PREEMPT Tue Jul 23 11:32:45 KST 2013 armv7l
PHP Version: 5.5.15
Zend version: 2.5.0
OS : Linux, linux
Debug Info: array (
  'tps' => 0,
  'memory_usage' => '10.1MB',
  'memory_peak_usage' => '13.43MB',
  'entities' => 0,
  'players' => 0,
  'events' => 1,
  'handlers' => 5,
  'actions' => 14,
  'garbage' => 0,
)


Parameters: array (
  'input' => 
  array (
  ),
  'commands' => 
  array (
  ),
  'flags' => 
  array (
  ),
)


server.properties: array (
  'server-name' => 'Minecraft: PE Server',
  'server-port' => 19132,
  'gamemode' => 1,
  'max-players' => 20,
  'spawn-protection' => '-1',
  'whitelist' => false,
  'enable-query' => true,
  'enable-rcon' => false,
  'description' => 'Server made using PocketMine-MP',
  'motd' => 'Welcome @player to this server!',
  'server-type' => 'normal',
  'memory-limit' => '128M',
  'last-update' => 1408100606,
  'announce-player-achievements' => true,
  'view-distance' => '10',
  'allow-flight' => false,
  'spawn-animals' => true,
  'spawn-mobs' => true,
  'hardcore' => false,
  'pvp' => true,
  'difficulty' => 1,
  'generator-settings' => '',
  'level-name' => 'world',
  'level-seed' => '',
  'level-type' => 'DEFAULT',
  'rcon.password' => '******',
  'auto-save' => true,
  'server-ip' => '',
  'white-list' => false,
  'send-usage' => true,
)


Loaded plugins:


Loaded Modules: array (
  'Core' => '5.5.15',
  'date' => '5.5.15',
  'ereg' => false,
  'pcre' => false,
  'sqlite3' => '0.7-dev',
  'zlib' => '2.0',
  'bcmath' => false,
  'calendar' => false,
  'ctype' => false,
  'curl' => false,
  'fileinfo' => '1.0.5',
  'filter' => '0.11.0',
  'ftp' => false,
  'gmp' => false,
  'hash' => '1.0',
  'json' => '1.2.1',
  'mbstring' => false,
  'mcrypt' => false,
  'standard' => '5.5.15',
  'SPL' => '0.2',
  'pcntl' => false,
  'mysqlnd' => 'mysqlnd 5.0.11-dev - 20120503 - $Id: bf9ad53b11c9a57efdb1057292d73b928b8c5c77 $',
  'Phar' => '2.0.2',
  'posix' => false,
  'pthreads' => '2.0.8',
  'Reflection' => '$Id: 31d836a7ac92a37b5c580836d91ad4736fe2f376 $',
  'shmop' => false,
  'sockets' => false,
  'mysqli' => '0.1',
  'tokenizer' => '0.1',
  'Weakref' => '0.2.4-beta',
  'yaml' => '1.1.1',
  'zip' => '1.11.0',
)
Memory Usage Tracking: 
AwA=


phpinfo(): 
7Vzrc9s4kv/OvwKVnbpJ7qz3y8putk62lcQ7sqWVlMxl9u5YEAlJjEmCw4dtue6Pv24AJEGKlOPd
2dR+mKRMgegfXo1Gd+PFYB84/pa/fmMsPi7IZxZGDvfJuz+TQXPQ7AwMY3WIYuZhzMzxk0ficou6
ex7FpNdsN3udRqcz6ncHI/KHDlndLMhiOZ3eLNZknTDyl8Ql3R7pdN72um/7A/LTak267U6P0NC7
H7nGReK4NrmiMcP8J8mOkAEC+qQzftvtv+2PjUvub51dEjJyyT2P+jYiyY/NlpUSfoTXRoP5dOOy
huO7js8aPIgdz3miMTTmRyQHIds6j+9a9zRsuc6m9ZX5d44ftb7yTdSCljcW3Lpj8Q0mnvh2yB27
9cDDuyigFoOyvMBx4TfkUZS+UAlriLa0No7fCvbBQJTGHpn1nYt8cOJ9w0pC97sW+ATlfPcCG7YT
ftdCD9T7vmz1rPAQxN+1yJ0XfM/yeBI3fBDXiEWFuJBRG0fwj9qY9jZRHDr+To8DHcR8m4Z63AOj
dzDm9Kgg3mOOUVVcI2A29WPHEkTbiQQVmv/ouYWo8rvNvcJ75HiByypSYTEsLMc+hE5cirV2TjFH
FkWp5spKZZtkV4gJbF7gXcAUP9IIB3TkfRFi80b0qwsVyHs+UBxI2bMvctWKD0GhOyIhCwWWRpCG
2e98XoiMQf1a7w6sBPV4UOhd6vgx/LGw8aRyzdiw52HciOmukMMTdDzwfOdTt9ivlh+7egTzNsy2
md3wDtjmQqEY49vaiBOQd3q8gm4sj8b7AkeKeT05hfZs40BTV1jXe+/dh/l6LmLRcL6DMdFI/Duf
P/ggb2BUGwnkubF2fsLoxjlmIqLuCqxxgvuhjuOBRa09wy4wViy8ZyGZLK7RVqZmE6w3I9c+iN4W
Bq3x2QnjhLrkygmZFfPwQFZJEAC/MY3M1M6Mr7Cj5D2Ma/IahnHT8Z03ZAFsQfA/X2tg7saMw2Cy
SUWVoA6vfe6zN8bKoj6J905EwESQLQ8JtW0HkdBSrDXZQoJISzGppAcUFJOtwdA3UvwE96Tb6XR6
Im76GDM/9ZgEBf4bv0Cvl0h1NOkBofOzuM5AZ+tVKfcCTENdoVLIqT431kK5kRXdsvig96UoeCWG
DfkIfAaR2h3Rb5iHonBDfboDEToiJ27sbA7grmnCEoT83sGu2RxIqqqN68X9UAcpubWNq3UIvV9J
MpZs54CzCaqEYPNXMTTFE72F8hGCUmyi/T8jIBRnoqvOyM7lEGHTmJ6RfRxjPD5Qi50RGJp6pjJD
shJiSaAifoSVECXEFqRKbHz4ziMGdxVJQd7gXSTAmjT//YxIWy1CNsvCkg3NkMedXvYWc2g1C7V3
lz9o7/gTmKjvzgiqbhaKvCAYJR6zoZnM2oPiMKCXQcaB8bsQKuXRO5DZJGKEb0H6GZFdbUFmMXby
jPq7BPqTTP0djMW3SgbFC7nvgp/fPoNxFRxCZ7ePyWvrDbjf4/OGcMQFdg3l+lDZncMiwzCI+dv8
g6wKw9kwpLI1jIvLG9Qu0bFKMqTCcu7FuJ/hZIR8pm4iXm8odpd8V3k1I3QVkNgWD8NIXQcoXIUq
y7nkITPqJkXfXAnqQheb4JabWx4wkcdcPTWa41tuYovU8+1W/QD9gR4iM+BB4sIUyQzpA7xEsYnS
XsaGOzNioLco6HLQZEEiWvNv4lGigiNQIkdS6sp5JjE3KUisb5tbpWh9Tu7ThqZhCcSBCBbZ/OrE
xVYiEQbv89lsQv4AvRXUAmy2paCBTGuP+lkUk8TbxnklyHM8hq6LGNzsMW7tY88tvBhK85iWS6NI
moXqchVum/gWyulJZODSg8nCkEs1sVpfzT+t81AGAcsOFjjQoIplwHmbW2bIeVxfDrfA0zWhJc9B
TmYjhd203UKPqdhM1Ey0KMpa5CCsdiodUn/VFyOwoD6eQaRS8k3ZARaGrML1uqPhqAh6dGKT+2YM
YsCltGuizR6hddDEfVBsVGpwTfQfvptvg4FWVnbU8rn09tEhbqTm/l+sOgYOZTMJXHDLogIT92BF
XLQkTSjKY77g/Z+2HAJRfHDZu1cWmJLwLfnD+/fn7Xb71Z9V4E8tBP35hXCtPDX0azOARO2LC8hA
Bp4rrxqulZdqlNrUorYy8C2FHcO1wu7YAXrUPpHBaKQywMDz5VXBtfLyQViZ/upK1VcGniuuGm4g
B3UNmI9QcFTBAOMoZ2D77G8DRTwJLVYNAv8I9NVGmXmdDrN3xwJtsXWTaF8QZWWXzUBNddCrfNtq
tSIwo+BQtZgnLLPdarfyAagFGzeLJqZpYeLmWwNUYHVDcoLp0UfTlZ5Cp93tp78GzJPdJkxnzEdz
L9YVSlkIOkx5LIZmIaQmmnswgcpdrdSkIs0pvYyVwcXMBM2e0KWaJ4XEshbotuVTEIUbYvosQjUN
jbpnYrgM+/KpYdKcGx351Eig8iLJhHY7/TU8MU8xXceT3kane36T/hroaJkbCjM4qcQrWyadIHOT
bLcsFXTVLkXa4ySJ1ecg7CPWM3KeBEVWASoAdsxyUpexI7uwb4AVdVGQTDFTz1J1hj+pnzIijl3Z
prb6AYCckJjg0Fn4uC+IqzSJJjDHZfQuqqLhgoQptHlJfEL2awIdZYKKOdHmCJKj0JjbkHvPo9Jx
00qisBWhjUlJpBGThkNOEiGf0KEu8MkscnQkn4ZYHzJFd4P7WmrQ6ma9wHC+X6G/GJEXB2bq9HcH
8mlEv7rNCKbOpseP3PEIfPGYeYF5Sqxg4Fl31WM88fP2QC3cDSLRpazNTI4rMx1nqcR0b+QzpcfP
1ElovmcBju80C3LXk+MNfnIAVsOncqw2MVYsmugvBoxXB/3HKBel6YfF5SoLGLgyGliSSaafeBuJ
UqNPp5ZZiNILVj6GuZcJ03Qr7aRUyAVdua8765jkZesXFflGYsJsMh+yPeV+SrBYSIGZCLPuSpkZ
YsVU/ZDCnCGbXOJGDTw/LWdVc08Rf+2DMvfkMhfQRs3eqNluXE0/G5OdqFDPeA9WLwlhSj6JDr61
v7oVTP4CEZdgdGBqLdTDLVfLRDL8YbVq3LIdjx217QZx11e3aQjXbWTwLtz0VXAGqoalczfMH7zE
pzR8u57dKBwGf75QL6vF7fTDPH1ZzVL8aiUX0iB2PVs1VsuFeluEPObgMAhWydWdrVrQidLFHXxG
xkc1nJ9ZSBWlarP3BXdpCHGtTrPXHBm/zJyNTu40u81zw4ApD5PPljBLFR30au5G3H9F1kB/4j7D
LUyKFkfPDpdPmgPjGAM0B9dhQYCgZ6TLGqcoIH64Wb9ghQErmnq+JngjTqxWEnqd5mgoZ0UqWMJy
f5eDB81ur9fTghIcJX7owEwJhN6Runzcbg7OewqbvWRomJd/I1hvcuVAg4ke24lVQfZIoK9CGooV
zYsEDbNNXBWVjSqUGdzMzkNVnXev9zhUSaCBn4ZxLZZNgK2OLccdrpvLJb/SYumS3Wfm6Idr+y3p
273z8Zi1z8dsyPqDTWcwGo8GFmPbLrVGYHCHbGyPhl3ywwu6VtZLn9YAf9E6hfSh+FaCgiurlnOq
GQsjyjDeg32sWvjaeYF4VBE/3CyIxr8h8K9tGHsa7eWzKs1HiEf2yQVHUSvP7sJfH/4GJNrTDj66
4Oviz2CIP71z8TaAeS9oZebZ4NmloWFbhRArQz3wkR72TugGnLswmHYshARnPRUctrPguJsFAdDP
Af0cAEX7bBsm6geL2aHGoegP9rrECq30uSFb/74Db/gDju1XTmlM9hQYLSsgg6ICMigqIILQ4iw4
GGYAUa0sWT9P1s+T9fNk/TzZIE82yJMN8mSDPNmAGMbXCNdc8VnVbyL+vqgeO4aRLfEblbsBaeqc
qCaSTK43oxPmbLzN1jU+rkEC5VJlZnRjXJR3M6uX7Q2oNMX69JrdvD4kW7EoLoi/isTSPWZD7qj/
1SHCbZADRoxwtdTOwldnKETWnogNJMx2k8DsDsYZOjK4sv7h9hOZsQh8HfKB+SyEobtINjB9BP1k
QeksqyDwqqmz6PVXGlAQf/aGhEKhRad4JiGvuY9r44lH3xD0FoVzSXKfwz+Z4l5fth4jq75Z8aQ8
TX2t05OCDJ32olnqRX2WmmLRLzI51BFdWH1SmQLQ0pvZQnZAoyj9LWHy5exnQSZ2dbYyLLD/+1qs
B/8fDXAVQFS59YjLEv/9H+CJvvkGSF5SatWf9yGzJG66N4NUlsQoUXkwx+EPdITsjxNsjRIIgVWP
mVglp1Z8ouMMuXeV/laJpKSYarRUAHSHpzkA/2kSOODMSQeojUuFI0OpBxhJlhPs1YKEBQLXQK0u
VGvofPVtylwREz/wrQPGhIbWliehhKIWdvmdMx5p4HGXoAkMAzeJyAMMe7Jx+QMmbuA6J6hiG7o5
wwvjAmhclARtQTM0NMfZeZSEVpfgJhy0DNJpFcf5oKz2xiLWdkOsOCTM2hAfX3wOD/yTuoa8ZKjJ
LUPq7ngITpMXnZypKbSozUmgIQ80gAbC3+vKzX3XQT7gtnbqSWkqQ52EANXRbnY6DZvdk4bY4W4P
2j0ICq9nsx1Te9DbdDrWmA5GbGtvOu3BqDvu2qPeZtw935xbA2s0Aq9nIrmxwBKg+VDwzPHlGkUb
HC96iqzSajEv4K/gQ1PutYnpPyiVdCqTzQ4LqCCvRAUmdbHSJYXqfipiU9b3eu1h+nuEefjW3OQB
nG9F48T8OaxYc0y5+8kXy2ry/EP2okOLDDqNh27ivg99VZ4lKwHLAjVK5beWw0t1kkBlH6Uj3LB4
CI6MnKbmscKpwMMNiuLzWKOmZ2vkKiJJF2j67fEQpgj0iIDbVOeSou1L9TqD3hBXNS+566JUg+EQ
535Ak1tRNqXPiXL1s4TB6TTo+9TqtGh6YgZ0I3hekcbMM7EAiFbaYmc0ifemxJiCbvoUB5aJVhR3
HCoQlstomAEMVCHZWZW8ICfv22JViYEuS2RGSoLa6h1khUHJ0h0wAirOmWmoNKaEU8sGwpvApXEY
4HUUxfFygSa/M2XmlVTGt6fIuBet1uSfhW0d5tom+B/0WWiIqqgeg5ulVGx+RAFwnZ3Cgivg79QW
iA7TWWxa+fnqY1YDh2oIwJwaisaXU4icJadQwI0acpkRNTCNBxIBeKFNIfNfE5jhM2VbfO6b9TQQ
Lps9YjaKUxshcMW4CM1IIaFUBLhFxWIVlfgVkUFkVsdWosWOFcT4uFLoVhCCqJiL4hWkYDAk1NZO
NpA0OvfFPpJOxtMZ5pbFFmaM6/+QNR40VKU/AwoiDZA1RSAs4YgcZ1OJKuRTKKiQTZb429A5d5/B
a/3zPPIlueJZaB5qOAoprTjr3CpKgRfRnRMEVfCUkKItHhzwZIQ4h2xGNFOkRQIYeVyAzolCO6jW
mzHnZgTluClV2HgzSiyLRVExcksdFy9w6JGOGGT5iCm4CSCKlRlKJ9HMsyjG527JMYQ9qk1ey+Wp
isg2frU4mPanRetIMHyObbvMBEuQckKjZ7lvQ8aU8iiVcUTJ0kSxV12tMgHMvsmQ59yCSiSpVdSj
qVeKt6rhVg0cdyCr8Gn8UQLRLKsqsgytrnhNvaurXVPrmkrX1bmqypU1ZjCb8+0kKINrogFegy7F
CrfExDWFTBn4STqSKogbpz4h+IMH50TGYou0lgop5QmDOuqJOu1OkW1mOZkWqqBvXU5PpObJxmX1
ZLVxVUk8gGd6glve6WxPApAIjqwX1HM7OzNTzTSXb2qJzE+8+oxZPbd2jIPzJLdGKgE83rMCTzaO
D7P9WuErkUviV6JWCGAJcSSCJfqREB7TT9ZudxpQIYolxJEwlnM4EscyoCSQJXJZJI846D2X+TOQ
SsEs98KRaJYZWRLOErksnuXs2SkOVoloCaIJqeM72Wwk80F1BVoAoHdRJAMFnG9HexMJ7I1OZmlt
8FVOQVwn0tJYIZ4pK6SyQx4UIkI0dfLMmIyI9kls8wdfiynMfGUcMACdGlPsUOYF6g6QDrtzcjfL
yw/vKFDWq/iWC4qEuvQgRhA44XrTylMhjIT+wFNodpKKkchPng8uxKX+UTaXlpxQJ5Mil94zvfng
w6hZRSlW9WwpFs8Aia3p7JS7RtScoSwOOoDFR5ngsaB0nVwjCGnTGQQ236+egoP3IE8/6w51LSh1
rg1xC039VG6vBpa4V3C5nJLXCxa6eEErABlBFbNku8QFZTF9TNeoojdVS7cidbojri2WnTd7fXHB
utHpNl50TwFr1cz2mLSDdfI4qhaUUMg2EcWWoXkIGrnHWxb4fCsu9ExCa491qWALgsj0v9b6EnS3
2W52JQVXmApbf/DfWH2+JWF5I54O+ufn496Inrf7vZ7d7/Xpdjga9OyevTkfdEZbRrfjjr0lP4ic
G+KcoDjYidsNWL3CSZ3185BfrhfPQXZPTpDdYVK1TWkboHXLxHTfk7yGsRvjNCtgltvaPHXfGPOA
+bgaGR1focrhuGGFB+OiyH1jyD4gspJQAF4UxVPjpuqQM8JDNKMgHRZO/IMY73JdwUA+kNWebp27
psxhC57CgaDUO0/ywtcHGPi4FnnB6L3aTr0BDiQRueAs3LEQUuIxfZyI4e0kyETclsVz4XJ/sHjx
qNtu9xrwGOPZGvITzo6fXNZ8gSBDPdU5tlSfV5/eRBxebOC+eyis8ysKWJCQmeJQg07FY5/Oo3F8
AgRkio7H4xGzR0OQPTboWeMOa1vsfNjd9kbt0bAz2gyBaz9AHuoKslHcPmvj8aMl27py6qqHa1bH
Rcm9jn3eG9IRtcZd2httBtbgvA0x9rhD7f6oN9wyrMEQSxbXb9VPpXpSt3sNQ96Si6rUj7FazMSj
Kofsimkkb5+CWUbCGZmDsg+v4Q8vIZ2BrhMa5J7lUSvG7hCrxQTufCNXkMTLKtl8BYYYl/mNnYm4
gpInmYQhPZRe5yLVGbmg9nt1Hu8SRsn0EWUdXgTlhsV7bpfiL0GSwMLm+V2qk5vyWFAen92j1aI4
3m3WMpt6QazR8fJqJL6uUYgrZPsBvLL87drfoivD9Jh7PK40CXcJDimtsBSTY2fM38V7DTJD1a3R
+c6xNLI4XBDo3XHLl+zB0bkNnTrfXkAn25GWUsQu0cnQI6ETwdV+0KIW4BX4Wg3KSTIZKXVqFn/U
PRqlup8yQEWHZbTaRMdMzUjimFpF/DpkTI8uomB0gMumNRmE/ArnGwfc7WT2DHSYiERhwSOh2Usq
0+L1kdmCReL1I6OBCNw4fh6mj1lYJl3JSwwiZhE6uP18+GvCEhmTh1YxsFGE1swL9KI/4bmYUpd+
8tljIJYnhT7OKIYhvzvQA8Xx1xkGqpRHSvK4nbhMN/nt5gg3/xRCPw7Ya543+83eC5wdVZPm0XWv
6q10sKh4SxTvnh586onDPrL0KtcMj7zHnGRn2U+ecH/BRVI8dBQ3aQYWNyU6afxGFaVO0ajY9Jh5
/c1NiQNbBx4zu6cVeTzQ0FdzjLRIvNGpTgbhtzpgboiHXSItbXGrWr+EN2zLp3HyBgFeig2Z/FJG
M72aSt+B1dyegc5QoS1ecHkXhdYZrlS/OxPTOPD9370MLY+3w1Dw690FI+Z3zAevBxzadRqstI0/
y6+QyACMd1z/99Eanj48A65us9/YsJgaBn5vxjBAyL5MbmaVh+vk8Phc9ojTJIV8O83+C+QMy27a
DM/IqSm61q06sbjooNHTo1bU575jFURKp+OemWS4uNrYLRAfHFseID5vy6dh4F1+4xcn0PmQfyCh
7BO1B7bdYZbV7XTaowH+9XubNtueW4zBBMG2u93x1rJwGoB5FucWnWYbWflUJAAn23gAEi/+G/Lw
eEXXqA8F/Bzi1djw6NsFb1sto/AtgexTAo6/xbtkZ/INBhC+ieMKuL5xfE5d2oeK8+vf3NWioOxg
XGH+od+NqEbl17myO1s68rnLU/qHN6Q0g8upxPoWxqlhTP17J+Q+ejXgJqtLJZiHrPz05tNssp5e
mav1fDn5MDVX80/Ly6lQt54ft6I9c93sgp4xub1azq8BPb/8abo2nw47LpcexsZqejm/vZosv6RZ
iTyyK36P8QqcwtB+m0V9ijZXITolx1EXx1GXx1FXx1HT46j3eaWP62WsbxZX18tiVStvI8ZekGV0
MZ+vZ3N5KaNjwHR7urydzKrbnWbmsh21DlkWk9Vqul5JqPBdWyDoxmKy/ijjQGe8bd2DReBhS4QV
KtJf9PAjvBgT6ATzZv7pdr2YX9+us16EGatlzObzRRWRbzYGtuhyBpXKayCzFdoer0C38GBP8yte
3KwkNb4m4FLXADbg2VoHPH/o1uUBAlJDyULP0bs1gJi5LNhz/4CHGT3u18A8LzoNUFe9mwF3HetQ
A8JZlgN2qi6PAOfU+P2q2vSWyWyvnmpBOKR1dCvkrhtQMMV1iJgeQi4XDeogHg1jMfWUbaktq76S
3IoCpB7rl/Vk+WG6rhwj2eC4mqwnAoFrgsbsypxdXyxRs2TSqUaGsASqfDQnaQZLEGdNirP4xXK+
mC7XX8yf58ufQNalojs/Gw4Hw7b6Skl6765KW5qr6fLzdPm3VzVq89X/1CnOLGWlBpXpxjnqSJmq
nP8V1OlxU6qqmMOkii03oFbJHmWfaluZQ0frhJLirStCqd6jjKUOTlPlWjgDoril5L9PIedlFjWz
JihCN2e4kpLWcKimM1hBXxdb8LvG/l1j/yMau17HSdVdM8qOhxdqcQUWejyX8aJCV5galX6ULer2
gsQfQ47VvEyQKvp8gH9cQHj2/puU0/H3KDR9fbm8XqzN28nN9LfK6/31bPqb5Ic8NtfLye1KdOc/
nN/V/PLTzfR2rfVETlxO//ppulqb6+ubqfl+Np8oRKffPu+028M2zK3Oz0fVCcrQHIXfaJBUsT5n
vDYI/Ptb++9syxujkLWVmZbp7ee/x7iLZKctu4D8S5v1YiOqbbrAvNSgFzI+suaS5S805YUsa+24
QP0GRlyW9owFF6BnzLfA/G67f7fd/yzbXa2/njHchcF0ZLWlXL/IZBcyrLDXBfpzxlrMytS14OIH
OyGIB05JxLfxAw3ZH8mBJwS/XRuy/N4xcWLcT2/xELdDnO3BgIj8KnLMQi9Kv/ipFUUoFIR3kvEC
AG7Rp/QPIU8CA3fo1WetMCCoWZm4+qfi8IrcW0Jm15fT29XUOGqAfj9aJdnzAKq1pzHW/AEPLW0Y
3sLeJu6ZAUjy8/X6I34McXL7hfw8WYJlX3/5I1HfpiYMekXkIw5AQ7bAmpD68QEaadxMl5cfAT+5
uJ5dr78QYMr76/XtdLUi7+dLMiGLyXJ9fQnysySLT8vFfDVtGsb1VnDWdmxxcUud2yGU4FF3nXeu
5B0ehMAr8gDxD4b4IJI4uUA3WMEc6Pi7MxK4DL/mYXE/placZvGf+H1kn8VN4/8B


```

So I didnt kmow how to uploadtext files sorry. Ps is pocketminedroid a ripoff?
Pss:I have a galaxy tab 3 8.0

**Comment by PEMapModder** [comment]
Read the contributing guidelines before creating an issue, and please don't report bugs in older versions.

**Comment by MCMrARM** [comment]
It's not an older version.

**Comment by PEMapModder** [comment]
It says ConsoleAPI.php, and sorry I thought this is the PocketMine-MP repo.

**Comment by NotaGames** [comment]
MCMrARM thanks for agreat app I wanted to have pockrpetmine but I couldnt because I dont have a working pc, ps:didnt fix, just saying thanks for a  great app

**Comment by NotaGames** [comment]
MrArm could I have a contact  could ihave somecontact info so ican send some bugs or shouldi just post them here?
